services:
  minio:
    image: minio/minio:latest
    container_name: captraw-minio
    environment:
      MINIO_ROOT_USER: Capt-Docs
      MINIO_ROOT_PASSWORD: "12345678"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 10



  postgres:
    image: postgres:16-alpine
    container_name: captraw-postgres
    environment:
      POSTGRES_DB: captraw_db
      POSTGRES_USER: captraw_user
      POSTGRES_PASSWORD: captraw_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U captraw_user -d captraw_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  minio_data:
  postgres_data: